development:
  adapter: mysql
  database: 4everRememberME_v1_dev
  username: root
  password:
  host: localhost
  port: 3306

test:
  adapter: mysql
  database: 4everRememberME_v1_test
  username: root
  password:
  host: localhost
  port: 3306

production:
  development
